version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - "3306:3306" 